# Generated by Django 4.2.9 on 2024-01-21 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vmachine',
            fields=[
                ('identifier', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_time', models.DateTimeField()),
                ('product_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.product', verbose_name='product')),
                ('user_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('vmachine_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.vmachine', verbose_name='machine')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_number', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('product_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.product', verbose_name='product')),
                ('vmachine_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.vmachine', verbose_name='machine')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_nr', models.CharField(max_length=255, unique=True, verbose_name='card number')),
                ('active', models.BooleanField(default=False)),
                ('funds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('vmachine_fk', 'slot_number'), name='unique_slot'),
        ),
    ]
