# Generated by Django 4.2.9 on 2024-01-15 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vmachine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_time', models.DateTimeField()),
                ('product_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.product')),
                ('user_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vmachine_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.vmachine')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_number', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('product_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.product')),
                ('vmachine_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.vmachine')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('funds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
