# Generated by Django 4.2.9 on 2024-01-21 18:55

from django.db import migrations


def create_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')

    admin_group = Group.objects.get(name='Admins')

    User.objects.create_superuser('superadmin', 'superadmin@example.com', 'superadmin')
    User.objects.create_user('admin', 'admin@localhost', 'admin', is_staff=True).groups.add(admin_group)
    User.objects.create_user('user', 'user@localhost', 'user')


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_create_groups'),
    ]

    operations = [
        migrations.RunPython(create_users)
    ]
